sourceflag:
  switch-logger:
    global-success-response:
      use-default: false
      response-entities:
        - code-field: code
          code-value: 200
        - code-field: code
          code-value: 100
      message-fields:
        - msg
        - message
