sourceflag:
  switch-logger:
    global-response:
      response-entities:
        - code-field: code
          code-value: 200
        - code-field: code
          code-value: 100
      error-message-fields:
        - msg
        - message
