server:
  port: 8081

spring:
  application:
    name: switch-loggeer-test
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置 nacos 注册中心地址
        cluster-name: ShangHai
        metadata:
          version: v1
    # 如果使用 spring cloud loadBalancer 的话，需要剔除 ribbon
    loadbalancer:
      ribbon:
        enabled: false

sourceflag:
  switch-logger:
    sky-walking-trace: true
    global-success-response:
      use-default: false
      response-entities:
        - code-field: code
          code-value: 200
        - code-field: code
          code-value: 100
      message-fields:
        - msg
        - message
    rpc:
      feign:
        enable: true
        succeed-codes: [100, 200]
      forest:
        enable: false
        succeed-codes: [100, 200]